import React, { useState } from "react"
import styles from "../styles/Home.module.css"
import Xoutline from "../assets/icon-x-outline.svg"
import Ooutline from "../assets/icon-o-outline.svg"
import X from "../assets/icon-x.svg"
import Head from "next/head"
import Image from "next/image"
import O from "../assets/icon-o.svg"

export default function Game() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={``}></main>
    </div>
  )
}
