import React, { useState } from "react"
import styles from "../styles/Home.module.css"
import Xoutline from "../assets/icon-x-outline.svg"
import Ooutline from "../assets/icon-o-outline.svg"
import X from "../assets/icon-x.svg"
import Xgray from "../assets/icon-x-gray.svg"
import Ogray from "../assets/icon-o-gray.svg"
import Head from "next/head"
import Image from "next/image"
import O from "../assets/icon-o.svg"
import iconRestart from "../assets/icon-restart.svg"

export default function Game() {
  const [squares, setSqaures] = useState(initialSquares)
  const [choice, setChoice] = useState()
  return (
    <div className={styles.container}>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main
        className={`sm:w-[28.75rem] sm:h-[38.938rem] w-[20.5rem] h-[32.25rem]`}
      >
        <header className={`flex justify-between items-center mb-5 `}>
          <div className={`flex justify-between items-center w-[73px]`}>
            <Image src={X} alt='X' width={31} height={31}></Image>
            <Image src={O} alt='O' width={31} height={31}></Image>
          </div>
          <div
            className={`flex justify-between bg-[#1F3641] items-center py-3 px-8 w-[140px] rounded-xl mr-3 ${styles.shadowGreen}`}
          >
            <Image src={Xgray} alt='xGray' width={20} height={20}></Image>
            <h1 className='font-bold text-[#A8BFC9]'>TURN</h1>
          </div>
          <div
            className={`w-[52px] h-[52px] flex items-center bg-[#A8BFC9] justify-center rounded-xl mr-3 ${styles.shadowGray}`}
          >
            <Image src={iconRestart} alt='restart icon' />
          </div>
        </header>
        <div className={`flex flex-wrap`}>
          {squares.map((square) => (
            <span
              key={square.id}
              className={`w-[140px] h-[140px] bg-[#1F3641] mr-[13px] mb-3 rounded-xl ${styles.shadowGreenXl} ${styles.squareX}`}
              onClick={() => console.log(square.id)}
            ></span>
          ))}
        </div>
        <div className={`flex justify-between mr-3 text-[14px]`}>
          <div className={`w-[140px] text-center bg-[#31C3BD] p-1 rounded-xl`}>
            <h2>X(YOU)</h2>
            <h1 className={`font-bold text-[24px]`}>0</h1>
          </div>
          <div className={`w-[140px] text-center bg-[#A8BFC9] p-1 rounded-xl`}>
            <h2>Ties</h2>
            <h1 className={`font-bold text-[24px]`}>0</h1>
          </div>
          <div className={`w-[140px] text-center bg-[#F2B137] p-1 rounded-xl`}>
            <h2>O(CPU)</h2>
            <h1 className={`font-bold text-[24px]`}>0</h1>
          </div>
        </div>
      </main>
    </div>
  )
}
const initialSquares = [
  { id: 1 },
  { id: 2 },
  { id: 3 },
  { id: 4 },
  { id: 5 },
  { id: 6 },
  { id: 7 },
  { id: 8 },
  { id: 9 },
]
