import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import X from "../assets/icon-x.svg"
import Xgray from "../assets/icon-x-gray.svg"
import Ogray from "../assets/icon-o-gray.svg"
import Oblue from "../assets/icon-o-blue.svg"
import Xblue from "../assets/icon-x-blue.svg"
import O from "../assets/icon-o.svg"
import React, { useState } from "react"
import Link from "next/link"

export default function Home() {
  const [switchOn, setSwitchOn] = useState(false)
  let switchX,
    switchO = " bg-[#DBE8ED] "
  if (switchOn) {
    switchX += " bg-[#DBE8ED] "
    switchO -= " bg-[#DBE8ED] "
  } else {
    switchX -= " bg-[#DBE8ED] "
    switchO += " bg-[#DBE8ED] "
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div className={`w-[72px] flex justify-between`}>
          <Image src={X} alt='X icon' width={32} height={32} className='mr-2' />
          <Image src={O} alt='O icon' width={32} height={32} />
        </div>
        <div
          className={`${styles.choiceBg} w-full flex flex-col justify-center items-center p-6 rounded-2xl shadow-lg`}
        >
          <h1
            className={`text-[16px] font-bold text-center ${styles.textLightgray} mb-4`}
          >
            PICK PLAYER 1&apos;S MARK
          </h1>
          <div
            className={`${styles.mainBg}  flex justify-between mb-3 rounded-lg overflow-hidden`}
          >
            <div
              className={` flex justify-center items-center ${styles.switchBg} ${switchX}   rounded-xl p-3`}
              onClick={() => setSwitchOn(!switchOn)}
            >
              {switchOn ? (
                <Image src={Xblue} alt='X icon' width={32} height={32} />
              ) : (
                <Image src={Xgray} alt='X icon' width={32} height={32} />
              )}
            </div>
            <div
              className={`flex justify-center items-center ${styles.switchBg} ${switchO} rounded-xl p-3`}
              onClick={() => setSwitchOn(!switchOn)}
            >
              {switchOn ? (
                <Image
                  src={Ogray}
                  alt='O icon'
                  width={32}
                  height={32}
                  className={`${styles.img}`}
                />
              ) : (
                <Image
                  src={Oblue}
                  alt='O icon'
                  width={32}
                  height={32}
                  className={`${styles.img}`}
                />
              )}
            </div>
          </div>
          <h1 className={`text-[14px] ${styles.textLightergray}`}>
            REMEMBER: X GOES FIRT
          </h1>
        </div>
        <div className={`flex flex-col w-full text-[20px]`}>
          <Link href='/game'>
            <button
              className={`w-full font-bold bg-[#ffa909] hover:bg-[#FFC860] p-3 mb-4 rounded-xl ${styles.cpuBtn}`}
            >
              NEW GAME (VS CPU)
            </button>
          </Link>
          <Link href='/game'>
            <button
              className={`w-full font-bold bg-[#31C3BD] hover:bg-[#65E9E4] p-3 rounded-xl ${styles.multiBtn}`}
            >
              NEW GAME (VS PLAYER)
            </button>
          </Link>
        </div>
      </main>
    </div>
  )
}
